=== rodrigochav3s/ADHealthCheck/AD_Configuration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ad">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fsmo" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="forest" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="schema" type="xs:string" minOccurs="1" maxOccurs="1" />
										<xs:element name="naming" type="xs:string" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="domain" minOccurs ="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="pdc" type="xs:string" minOccurs="1" maxOccurs="1" />
										<xs:element name="rid" type="xs:string" minOccurs="1" maxOccurs="1" />
										<xs:element name="infrastructure" type="xs:string" minOccurs="1" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sites" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="site" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="subnet" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
										<xs:element name="adjacent" type="xs:string" maxOccurs="unbounded" />
										<xs:element name="link" type="xs:string" maxOccurs="unbounded" />
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rodrigochav3s/ADHealthCheck/AD_Configuration.xml
<?xml version="1.0"?>
<ad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="AD_Configuration.xsd">
	<fsmo>
		<forest name="forest.corp">
			<schema>dc04</schema>
			<naming>dc04</naming>
		</forest>
		<domain name="domain1.forest.corp">
			<pdc>dc04</pdc>
			<rid>dc04</rid>
			<infrastructure>dc04</infrastructure>
		</domain>
	</fsmo>
	<sites>
		<site name="PARIS">
			<subnet>192.168.3.0/24</subnet>
			<adjacent>GENEVA</adjacent>
			<link>GENEVA - PARIS</link>
		</site>
		<site name="GENEVA">
			<subnet>192.168.1.0/24</subnet>
			<subnet>192.168.2.0/24</subnet>
			<adjacent>PARIS</adjacent>
			<adjacent>NYC</adjacent>
			<link>GENEVA - PARIS</link>
			<link>GENEVA - NYC</link>
		</site>
		<site name="NYC">
			<subnet>192.168.4.0/24</subnet>
			<adjacent>GENEVA</adjacent>
			<link>GENEVA - NYC</link>
		</site>
	</sites>
</ad>
